
version: "3.3"
services:
    client:
        build:
            context: ./client
        ports:
            - "3000:3000"
        volumes:
            - ./client:/src/
            - nodemodules:/src/node_modules 
            - /etc/letsencrypt:/etc/letsencrypt
    server:
        build:
            context: ./server
        ports:
            - "4000:4000"
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
    nginx:
        depends_on:
            - server
            - client
        restart: always
        build:
            context: ./nginx
        ports:
            - "8000:80"
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
volumes:
    nodemodules: {}