
version: "3.8"
services:
    client:
        build:
            context: ./client
    server:
        build:
            context: ./server
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:3050"